### ISSUE TITLE
Декларативное описания формата обмена (JSON) для API Method (Метода)

### ISSUE THREAD

**Issue by pbazeliuk** [pbazeliuk/IHL#3]
## Описание

Необходима возможность декларативного описания формата обмена (JSON) для API Method (Метода).

- [x] Конструктор декларативного описания формата должен быть в обработке, которая включена в подсистему Plugins
- [x] Если обработка поддерживает функцию декларативного описания формата, в обработке должны присутствовать Форма: **APICreationForm** и реквизит обработки **APISchema** 
- [x] **MemorySavingOutput** и **FastOutput** в модуле обработки должны: обрабатывать ситуации когда есть описание формата и когда оно отсутствует (в этом случае вывод должен быть по умолчанию)
- [x] Передача **APISchema** из табличной части **Methods** справочника **IHL_ExchangeSettings** должна происходить следующим образом:
```1C-Enterprise
    StreamObject = Catalogs.IHL_ExchangeSettings.NewFormatProcessor(
        FormatProcessorName, Object.BasicFormatGuid);
    StreamObject.Initialize(APISchema);
```
- [x] Необходимо внести изменения в процедуру инициализации формата обмена (JSON) для обработки данных **APISchema**. Такой метод инициализации гарантирует что будет возможность использовать произвольный тип данных, а так же использовать различные версии схем для обратной совместимости
```1C-Enterprise
// Constructor of stream object.
//
// Parameters:
//  OpenFile - String - output filename.
//             Default value: Empty string.
//
Procedure Initialize(OpenFile = "") Export
    
    RefTypesCache = New Map;
    
    StreamWriter = New JSONWriter;
    If IsBlankString(OpenFile) Then 
        StreamWriter.SetString();
    Else
        
    EndIf;
    
EndProcedure // Initialize()
```
- [x] #10 Реализовать базовый вывод базовых типов формата JSON 
- [x] #11 Вывод свойства с типом "Object" при декларативном описании формата JSON
- [x] #12 Тесты проверки корректности вывода при декларативном описании JSON
- [x] Реализация иерархического вывода должна быть выполнена в таком виде: каждая колонка макета СКД на любом уровне - соответствует **Свойству** в формате обмена (JSON) на этом же уровне
- [x] если **Свойство** формата обмена (JSON) имеет тип: _Array_ или _Object_  необходимо найти макет СКД подчиненный текущему макету СКД у которого Имя совпадает с именем свойства JSON
